name: "demo-action"
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: pnpm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: pnpm-lock.yaml
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: install 
        run: pnpm install
      - name: build
        run: pnpm build
      - name: display dist files
        run: ls -la && ls dist/
    # - name: publish
    #   run: echo Hello, world!
